print('Hello!')
print('What is your name?')
Name = input()
print('It is good to meet you, ' + Name)
print('The length of your name is:')
print(len(Name))
print('What is your age?')
Age = input()
print('You will be ' + str(int(Age) + 1) + ' in a year.')